AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model from the keras documentaion
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2 #healthy or diseased
WEIGHTS: imagenet #image weights
LEARNING_RATE: 0.01 # learning rate for the optimizer

## paramerters required for the deep learning model, we use to keep it independent of the model
